### ISSUE TITLE
Public exposure of API Key

### ISSUE THREAD

**Issue by iarthstar** [pexels/pexels-sketchplugin#1]
https://github.com/pexels/pexels-sketchplugin/blob/de3770edaccbdbfda0d802a8ed48a3525e511112/src/pexels.js#L6

**Comment by iarthstar** [comment]
I too develop sketch plugins, is there any way I can help or contribute to this repo...?

**Comment by sdougbrown** [comment]
Hi there, thanks for reporting this!

We agree that it can be a bit shocking to see an API key exposed like this, but in this case it isn't really a security concern. Our API is free to use and publicly accessible, and keys can be easily requested by any registered user. (https://www.pexels.com/api/).

We use the API keys primarily for rate-limiting. Given that it's pretty easy for anyone to acquire a key we're not too concerned that it might be scraped off github at this point.

If you have any proposals to improve this plugin, please create a new issue detailing what you'd like to help with. If it lines-up with what we'd like to see as well, we'd be happy to accept a pull request. 😄
